name: Project submission
description: Suggest a student project for inclusion
title: "[Project] "
body:
  - type: input
    id: author
    attributes:
      label: Author and cohort
  - type: textarea
    id: summary
    attributes:
      label: Project summary
    validations:
      required: true
  - type: input
    id: dataset
    attributes:
      label: Dataset source and license
